post http://localhost:3000/register

{
    "name": "manikandan",
    "email": "manikandansitti@gmail.com",
    "phone": "1234533333",
    "password": "Mani@4515"
}

###

post http://localhost:3000/login

{
    "email": "manikandan@gmail.com",
    "password": "Mani@4515"
}

###
get http://localhost:3000/image/_DSC7274.JPG

###
get http://localhost:3000/baner/_DSC7274_copy.JPG

###
get http://localhost:3000/get-categories

###
get http://localhost:3000/categories/laptop.jpg

###
get http://localhost:3000/get-baners

###
GET  http://localhost:3000/get-products/mobile HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMyNzAxMTV9.QN0sUW506hv80UUGU7FZkjDJu7LXtKPEG_uf_8ZkTsA


###
post http://localhost:3000/add-product

{
    "name": "realme 5 pro",
    "url": "mobile.jpg",
    "category": "mobile",
    "price": 15000,
    "available_stocks": 1000
}

### 
get http://localhost:3000/get-product/61f25430de96191e502c0a20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMyNzAxMTV9.QN0sUW506hv80UUGU7FZkjDJu7LXtKPEG_uf_8ZkTsA

